src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
use Gedmo\Mapping\Annotation as Gedmo;
/**
 * User
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{

    /**
     * @var int
     *
     * @ORM\Column(name="id_user", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idUser;

    /**
     * @Assert\NotBlank
     * @var string
     * @ORM\Column(name="username", type="string", length=20, nullable=false)
     * @Groups("users:read")
     */
    private $username;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="password", type="string", length=20, nullable=false)
     * @Groups("users:read")
     */
    private $password;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="first_name", type="string", length=50, nullable=false)
     * @Groups("users:read")
     */
    private $firstName;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="last_name", type="string", length=50, nullable=false)
     * @Groups("users:read")
     */
    private $lastName;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="adresse", type="string", length=60, nullable=false)
     * @Groups("users:read")
     */
    private $adresse;

    /**
     * @var int
     * @Assert\NotBlank
     * @ORM\Column(name="telephone", type="integer", nullable=false)
     * @Groups("users:read")
     */
    private $telephone;

    /**
     * @var string
     * @Assert\NotBlank
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     * @ORM\Column(name="email", type="string", length=60, nullable=false)
     * @Groups("users:read")
     */
    private $email;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="photo", type="string", length=400, nullable=false)
     * @Groups("users:read")
     */
    private $photo;

    /**
     * @var string
     * @Assert\NotBlank
     * @ORM\Column(name="role", type="string",length=100,nullable=false)
     * @Groups("users:read")
     */
    private $role;
    /**
     * @var null
     */
    private $plainPassword;
    private $salt;

    /**
     * User constructor.
     * @param int $idUser
     * @param string $username
     * @param string $password
     * @param string $firstName
     * @param string $lastName
     * @param string $adresse
     * @param int $telephone
     * @param string $email
     * @param string $photo
     * @param string $role
     */

    public function __construct()
    {

    }

    /**
     * @return int
     */
    public function getIdUser(): ?int
    {
        return $this->idUser;
    }

    /**
     * @param int $idUser
     */
    public function setIdUser(int $idUser): void
    {
        $this->idUser = $idUser;
    }

    /**
     * @return string
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * @param string $username
     */
    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    /**
     * @return string
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * @return string
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     */
    public function setFirstName(string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * @return string
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * @param string $lastName
     */
    public function setLastName(string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * @return string
     */
    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    /**
     * @param string $adresse
     */
    public function setAdresse(string $adresse): void
    {
        $this->adresse = $adresse;
    }

    /**
     * @return int
     */
    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    /**
     * @param int $telephone
     */
    public function setTelephone(int $telephone): void
    {
        $this->telephone = $telephone;
    }

    /**
     * @return string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    /**
     * @param string $photo
     */
    public function setPhoto(string $photo): void
    {
        $this->photo = $photo;
    }

    /**
     * Get role
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * @param string $role
     *
     */
    public function setRole(string $role): void
    {
        $this->role = $role;
    }


    public function getRoles()
    {
     //   return array(‘ROLE_USER’);
    }

    public function getSalt()
    {
        return $this->salt;
    }

    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\Coach;
use App\Entity\Member;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Gregwar\CaptchaBundle\Type\CaptchaType;
class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('password', PasswordType::class)
            ->add('firstName')
            ->add('lastName')
            ->add('adresse')
            ->add('telephone')
            ->add('email',EmailType::class)
            ->add('photo',FileType::class)
            ->add('role',ChoiceType::class, [
                'choices'  => [
                    'Vendor'=>'Vendor',
                    'Member'=>'Member',
                    'Coach'=>'Coach',
                ],

            ])
        ->add('captcha', CaptchaType::class, array(
        'width' => 200,
        'height' => 50,
        'length' => 6,
    ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
    /*public function getName()
    {
        return 'array_choice';
    }*/

}

src/Controller/UserController.php
<?php

namespace App\Controller;
use App\Entity\Coach;
use App\Entity\Member;
use App\Repository\UserRepository;
use App\Entity\User;
use App\Form\UserType;
use App\Entity\Vendor;
use App\Security\UserAuthenticator;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use phpDocumentor\Reflection\Types\Integer;
use Swift_Mailer;
use Swift_Message;
use Swift_SendmailTransport;
use Swift_SmtpTransport;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Exception\ExceptionInterface;
use const http\Client\Curl\POSTREDIR_301;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use App\Controller\CommandeController;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{

    /**
     * @Route("/", name="app_homepage" ,methods={"GET","POST"})
     */
    public function homepage(Request $request,UserRepository $repository):Response
    {

      $users = $repository->findAllPublishedOrderedByNewest();

        return $this->render('user/index.html.twig', [
            'users' => $users,
        ]);
    }
    /**
     * @Route("/imp", name="app_imp")
     */
    public function imp(UserRepository $repository)
    {
        $users = $repository->findAllPublishedOrderedByNewest();
        return $this->render('user/imp2.html.twig', [
            'users' => $users,
        ]);
    }
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(): Response
    {
        $users = $this->getDoctrine()
            ->getRepository(User::class)
            ->findAll();

        return $this->render('user/index.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $encoder,\Swift_Mailer $mailer): Response
    {
        $user = new User();
        $vendor = new Vendor();
        $member = new Member();
        $coach = new Coach();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $password = $user->getPassword();
            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);
            $entityManager->flush();
            $role=$user->getRole();
            if($role=="Vendor")
            {
                $results = $this->getDoctrine()
                    ->getRepository(User::class)->findBy(array(),array('idUser'=>'DESC'),1,0);
                $a=$results[0];
                $vendor->setIdUser($a);
                $entityManager->persist($vendor);
                $entityManager->flush();
            }
            elseif ($role=="Member")
            {
                $results = $this->getDoctrine()
                    ->getRepository(User::class)->findBy(array(),array('idUser'=>'DESC'),1,0);
                $a=$results[0];
                $member->setIdUser($a);
                $entityManager->persist($member);
                $entityManager->flush();
            }
            else
            {
                $results = $this->getDoctrine()
                    ->getRepository(User::class)->findBy(array(),array('idUser'=>'DESC'),1,0);
                $a=$results[0];
                $coach->setIdUser($a);
                $entityManager->persist($coach);
                $entityManager->flush();
            }
            $email= $user->getEmail();
            $username = $user->getUsername();
            $message= (new \Swift_Message('test'))
                ->setFrom('work.itpidev@gmail.com')
                ->setTo($email)
                ->setSubject("Account name  ".$username."  Registred")
                ->setBody("your username is :".$username."your password is :".$password);
            $mailer->send($message);
            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
   /*
    public function statAction()
    {
        $pieChart = new PieChart();
        $datas = $this->getDoctrine()->getRepository(UserRepository::class)->findAll();
        foreach ($datas as $data) {
            $role += $data->getTemps();
        $username += $data->getTempLibre();
    }
        $pieChart->getData()->setArrayToDataTable( array(
            //  ['Roles', 'How Many Roles'],
            ['Roles', $role],
            ['Username',$username],
        ));
        dump($data); die();
        $pieChart->getOptions()->setTitle('Roles Stats');
        $pieChart->getOptions()->setHeight(400);
        $pieChart->getOptions()->setWidth(400);
        $pieChart->getOptions()->getTitleTextStyle()->setColor('#07600');
        $pieChart->getOptions()->getTitleTextStyle()->setFontSize(25);


        return $this->render('stats.html.twig', array(
                'piechart' => $pieChart,
            )

        );
    }*/
    /**
     * @Route("/{username}", name="user_show2", methods={"GET"})
     */
    public function show2(User $user): Response
    {
        return $this->render('user/show2.html.twig', [
            'user' => $user,
        ]);
    }
    /**
     * @Route("/count_users", name="count_users")
     */
    public function countusers()
    {
        $em = $this->getDoctrine()->getManager();
        $query = $em->getRepository(UserRepository::class);
        $total_users = $query->createQueryBuilder('a')
            ->select('count(a.idUser)')
            ->getQuery()
            ->getSingleScalarResult();
        return new Response($total_users);
    }
    /**
     * @Route("/trie_ASC", name="trie_ASC")
     */
    public function TrieASC(): Response
    {
        $em = $this->getDoctrine()->getManager();
        $query = $em->createQuery(
            'SELECT u FROM App\Entity\User u 
            ORDER BY u.idUser'
        );
        $users = $query->getResult();
        return $this->render('user/index.html.twig',
            array('users' => $users));

    }

    /**
     * @Route("/{idUser}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/recherche/{username}",name="recherche")
     */
    public function recherche($username): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $query= $entityManager->createQuery(
            'SELECT u
                FROM App\Entity\User u
                WHERE u.username = :query '
        )
            ->setParameter('query', $username);
        $users=$query->getResults();
        return $this->render('user/index.html.twig',array('user'=>$users));

    }
    /**
     * @Route("/{idUser}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $encoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/searchUserx ", name="searchUserx")
     */
    public function searchUserx(Request $request,NormalizerInterface $Normalizer)
    {
        $repository = $this->getDoctrine()->getRepository(User::class);
        $requestString=$request->get('searchValue');
        $users = $repository->findUserByUsername($requestString);
        $jsonContent = $Normalizer->normalize($users, 'json', ['groups' => 'users:read']);
        $a=json_encode($jsonContent);
        return new Response($a);

    }
    /**
     * @Route("/{idUser}", name="user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getIdUser(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }





}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'idUser': user.idUser}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.idUser) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-lg btn-primary btn-block" formnovalidate>{{ button_label|default('Sign Up') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/imp.html.twig
 <form>
    <table class="table">
        <thead>
        <tr>

            <th>IdUser</th>
            <th>Username</th>
            <th>Password</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Adresse</th>
            <th>Telephone</th>
            <th>Email</th>
            <th>Photo</th>
            <th>Role</th>
            <th>actions</th>
        </tr>
        </thead>

        <tbody id="all">
        {% for user in users %}

            <tr>
                <td>{{ user.idUser }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.adresse }}</td>
                <td>{{ user.telephone }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.photo }}</td>
                <td>{{ user.roles }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        <script type="text/javascript">

            $(document).ready(function () {
                window.print();
            });

        </script>
        </tbody>
        <tbody id="search">
        </tbody>
    </table>
    </div>
    </form>

templates/user/imp2.html.twig
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js%22%3E"></script>
</head>

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>
    <form role="search" id="nav-search-form" method="post" action="{{ path('trie_ASC') }}">


        <div class="btn-toolbar" role="toolbar" aria-label="Programmatic control">
            <div class="btn-group btn-group-sm" aria-label="Set Select2 option">
                <button class="js-programmatic-set-val btn btn-outline-primary mr-1 mb-1">
                    Sort by ID
                </button>
                <button class="js-programmatic-set-val btn btn-outline-primary mr-1 mb-1" onclick="print()">print</button>
            </div>
        </div>
        <b href="{{ path('count_users') }}">users :</b>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>IdUser</th>
                <th>Username</th>
                <th>Password</th>
                <th>FirstName</th>
                <th>LastName</th>
                <th>Adresse</th>
                <th>Telephone</th>
                <th>Email</th>
                <th>Photo</th>
                <th>Role</th>
                <th>actions</th>
            </tr>
        </thead>
        <input type="text" id="search" class="form-control" placeholder="Search">

        <tbody id="all">
        {% for user in users %}

            <tr>
                <td>{{ user.idUser }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.adresse }}</td>
                <td>{{ user.telephone }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.photo }}</td>
                <td>{{ user.roles }}</td>
                <td>
                    <a href="{{ path('user_show', {'idUser': user.idUser}) }}">show</a>
                    <a href="{{ path('user_edit', {'idUser': user.idUser}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
    </tbody>
    <tbody id="search">
    </tbody>
    </table>
    </div>
{% endblock %}
{% block javascripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
</script>
<script>
    $( document ).ready(function() {
        $("#search").keyup(function(e){
            /* La variable value va prendre la valeur insérer dans le champ de texte afin d’effectuer la recherche */
            var value = $(this).val();
            /* Ajax est lancé lors du remplissage du champ texte dont l’id est « search » pour faire la recherche */
            $.ajax({
                /* l’url est une chaine de caractères contenant l’adresse où la requête est envoyée */
                url : "{{ path('searchUserx') }}",
                /* La méthode utilisée pour transférer les données est GET */
                type : 'GET',
                /*Ici search value va prendre la chaine entrée par un utilisateur dans la zone de recherche et sera placée après l’url */
                data: {
                    'searchValue' : value
                },
                /*Cette fonction permet de vider le contenu du tableau pour recevoir le nouveau contenu*/
                success : function(a){
                    if(a){
                        $('#t tbody#search').empty();
                        $.each(JSON.parse(a), function(i,obj) {
                            $('#t tbody#all').hide();
 $('#t tbody#search').append('<tr><td>  '+obj.idUser+'  </td><td>    '+obj.username+'  </td><td>  '+obj.password+' </td><td>  '+obj.firstName+' </td><td>  '+obj.lastName+'  </td><td>  '+obj.adresse+' </td><td>  '+obj.telephone+' </td><td> '+obj.email+' </td><td>  '+obj.photo+' </td><td> '+obj.roles+' </td></tr>');
                        });

                    }
                    else
                    {
                        $('#t tbody#all').show();
                        $('#t tbody#search').empty();
                        $('#t tbody#search').fadeIn('fast');
                    }
                },
            });
            return false;
        });
    });
</script>
    <script>
public function print()
{
    window.print();
};

    </script>
    </tbody>
{% endblock %}

templates/user/new.html.twig
{% extends 'front2.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Registration</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>IdUser</th>
                <td>{{ user.idUser }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>FirstName</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>LastName</th>
                <td>{{ user.lastName }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ user.adresse }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ user.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ user.photo }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ user.role }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'idUser': user.idUser}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/show2.html.twig
{% extends 'front.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>

        <tr>
            <th>Username</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ user.password }}</td>
        </tr>
        <tr>
            <th>FirstName</th>
            <td>{{ user.firstName }}</td>
        </tr>
        <tr>
            <th>LastName</th>
            <td>{{ user.lastName }}</td>
        </tr>
        <tr>
            <th>Adresse</th>
            <td>{{ user.adresse }}</td>
        </tr>
        <tr>
            <th>Telephone</th>
            <td>{{ user.telephone }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Photo</th>
            <td>{{ user.photo }}</td>
        </tr>
        <tr>
            <th>Role</th>
            <td>{{ user.role }}</td>
        </tr>
        </tbody>
    </table>

{% endblock %}

templates/user/stats.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stats{% endblock %}

{% block body %}
    <h1><center>StatS</h1></center>
    <div class="robust-content content container-fluid">
        <div class="content-wrapper">
            <div id="div_chart"></div>

            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <script type="text/javascript">
                {{ gc_draw(piechart, 'div_chart') }}
            </script>

        </div>
    </div>
{% endblock %}